name: CI

on:
  push:
    branches:
      - dev
      - 'feat/**'
  pull_request:
    branches:
      - dev
      - 'feat/**'

jobs:
  build:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run:  apt-get install -y linux-libc-dev
      - uses: borales/actions-yarn@v2.0.0
        with:
          cmd: install --frozen-lockfile
      - uses: borales/actions-yarn@v2.0.0
        with:
          cmd: test
